const LOAD_POSTS_ACCOUNTS = 'LOAD_POSTS_ACCOUNTS'
const SET_POSTS_ACCOUNTS = 'SET_POSTS_ACCOUNTS'
const SET_SELECTED_POST_ACCOUNT = 'SET_SELECTED_POST_ACCOUNT'
const LOAD_POST_ACCOUNT = 'LOAD_POST_ACCOUNT'
const LOAD_LAST_POSTS_ACCOUNTS = 'LOAD_LAST_POSTS_ACCOUNTS'
const SET_LAST_POSTS_ACCOUNTS = 'SET_LAST_POSTS_ACCOUNTS'
const ADD_POST_ACCOUNT = 'ADD_POST_ACCOUNT'
const REMOVE_POST_ACCOUNT = 'REMOVE_POST_ACCOUNT'
const LOAD_SELECTED_POST_ACCOUNT_WIDGET = 'LOAD_SELECTED_POST_ACCOUNT_WIDGET'
const SET_SELECTED_POST_ACCOUNT_WIDGET = 'SET_SELECTED_POST_ACCOUNT_WIDGET'

export {
  LOAD_POSTS_ACCOUNTS,
  SET_POSTS_ACCOUNTS,
  SET_SELECTED_POST_ACCOUNT,
  LOAD_POST_ACCOUNT,
  LOAD_LAST_POSTS_ACCOUNTS,
  SET_LAST_POSTS_ACCOUNTS,
  ADD_POST_ACCOUNT,
  REMOVE_POST_ACCOUNT,
  SET_SELECTED_POST_ACCOUNT_WIDGET,
  LOAD_SELECTED_POST_ACCOUNT_WIDGET,
}