const LOAD_POSTS_ARTICLES = 'LOAD_POSTS_ARTICLES'
const SET_POSTS_ARTICLES = 'SET_POSTS_ARTICLES'
const SET_SELECTED_POST_ARTICLE = 'SET_SELECTED_POST_ARTICLE'
const LOAD_POST_ARTICLE = 'LOAD_POST_ARTICLE'

export {
  LOAD_POSTS_ARTICLES,
  SET_POSTS_ARTICLES,
  SET_SELECTED_POST_ARTICLE,
  LOAD_POST_ARTICLE
}