const LOAD_POSTS_ACCOUNTS = 'LOAD_POSTS_ACCOUNTS'
const SET_POSTS_ACCOUNTS = 'SET_POSTS_ACCOUNTS'
const SET_SELECTED_POST_ACCOUNT = 'SET_SELECTED_POST_ACCOUNT'
const LOAD_POST_ACCOUNT = 'LOAD_POST_ACCOUNT'

export {
  LOAD_POSTS_ACCOUNTS,
  SET_POSTS_ACCOUNTS,
  SET_SELECTED_POST_ACCOUNT,
  LOAD_POST_ACCOUNT
}