const ACTIVATION_REGISTRATION = 'ACTIVATION_REGISTRATION'
const REGISTRATION = 'REGISTRATION'
const SIGN_IN = 'SIGN_IN'
const GET_USER_DATA = 'GET_USER_DATA'
const SET_USER = 'SET_USER'
const SET_EMAIL = 'SET_EMAIL'
const SET_PASSWORD = 'SET_PASSWORD'
const SET_LIKE_POST_ACCOUNT = 'SET_LIKE_POST_ACCOUNT'
const SET_DISLIKE_POST_ACCOUNT = 'SET_DISLIKE_POST_ACCOUNT'

export { 
  ACTIVATION_REGISTRATION, 
  REGISTRATION, 
  SIGN_IN, 
  GET_USER_DATA, 
  SET_USER,
  SET_EMAIL,
  SET_PASSWORD,
  SET_LIKE_POST_ACCOUNT,
  SET_DISLIKE_POST_ACCOUNT
}