const ACTIVATION_REGISTRATION = 'ACTIVATION_REGISTRATION'
const REGISTRATION = 'REGISTRATION'
const SIGN_IN = 'SIGN_IN'
const GET_USER_DATA = 'GET_USER_DATA'
const SET_USER = 'SET_USER'
const SET_EMAIL = 'SET_EMAIL'
const SET_PASSWORD = 'SET_PASSWORD'

export { 
  ACTIVATION_REGISTRATION, 
  REGISTRATION, 
  SIGN_IN, 
  GET_USER_DATA, 
  SET_USER,
  SET_EMAIL,
  SET_PASSWORD,
}